name:                tophat
version:             0.1.0.0
#synopsis:
description:         Please see the README on GitHub at <https://github.com/timjs/tophat-haskell#readme>
github:              "timjs/tophat-haskell"
license:             BSD3
author:              Tim Steenvoorden
maintainer:          tim.steenvoorden@gmail.com
copyright:           BSD3
# category:            Web


extra-source-files:
- README.md


dependencies:
  - base-noprelude >= 4.12 && < 5
  - relude >= 0.5 && < 1
  - prettyprinter
  - mtl
  - transformers
  - text
  - unordered-containers
  - lens-simple


default-extensions:
  # Lifting limitations:
  - EmptyDataDecls
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses

  # Syntactic conveniences:
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - NumericUnderscores

  # Deriving:
  - DeriveGeneric
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  # - GeneralizedNewtypeDeriving
  - DerivingVia
  - StandaloneDeriving

  # Syntactic adjustments:
  - BangPatterns
  - KindSignatures
  - TypeOperators
  - MonadComprehensions
  - BinaryLiterals
  - NegativeLiterals
  - NoStarIsType
  - BlockArguments

  # Type annotations:
  - ScopedTypeVariables
  - TypeApplications
  - PartialTypeSignatures
  - NamedWildCards

  # Prelude and overloading:
  # - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLists

  # Type extensions:
  - ConstraintKinds
  - RankNTypes

  # Intermediate syntactic adjustments:
  - DefaultSignatures
  - PatternSynonyms
  - PatternGuards
  # - ApplicativeDo

  # Intermediate type extensions:
  - FunctionalDependencies
  - UndecidableInstances
  - GADTs
  - ExistentialQuantification

  # Advanced type extensions:
  - DataKinds
  - PolyKinds
  # - TypeFamilies
  # - TypeFamilyDependencies
  - QuantifiedConstraints


ghc-options:
  - -Wall
  - -Wcompat

  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints


library:
  source-dirs: src


executable:
  main: Main.hs
  source-dirs: src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
  - tophat
